import Head from "next/head";
import { useEffect, useState } from "react";
import axios from "axios";
import { useRouter } from "next/router";

export default function Home() {
  const [imageUrl, setImageUrl] = useState("");
  const router = useRouter()
  useEffect(() => {
    // Fetch a random image from Unsplash
    const fetchRandomImage = async () => {
      try {
        const response = await axios.get(
          "https://source.unsplash.com/1600x900/?business"
        );
        console.log(response);
        setImageUrl(response.request.responseURL);
      } catch (error) {
        console.error("Error fetching random image:", error);
      }
    };

    fetchRandomImage();
  }, []);

  const styles = {
    pageContainer: {
      position: "relative",
      height: "100vh",
      overflow: "hidden",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
    },
    backgroundImage: {
      position: "absolute",
      top: 0,
      left: 0,
      width: "100%",
      height: "100%",
      backgroundImage: `url(${imageUrl})`,
      backgroundSize: "cover",
      filter: "blur(5px)",
    },
    overlay: {
      position: "absolute",
      top: "50%",
      left: "50%",
      transform: "translate(-50%, -50%)",
      textAlign: "center",
      color: "#fff",
    },
    welcomeText: {
      fontSize: "24px",
      marginBottom: "20px",
    },
    loginButton: {
      padding: "10px 20px",
      fontSize: "16px",
      backgroundColor: "#4caf50",
      color: "#fff",
      border: "none",
      borderRadius: "5px",
      cursor: "pointer",

      ":hover": {
        backgroundColor: "#45a049",
      },
    },
  };

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={styles.pageContainer}>
        {imageUrl && <div style={styles.backgroundImage}></div>}
        <div style={styles.overlay}>
          <h1 style={styles.welcomeText}>Welcome to My Website!</h1>
          <button onClick={()=>{router.push("/account/login")}} style={styles.loginButton}>Login</button>
        </div>
      </div>
    </>
  );
}
